const customers = [
  {
    id: 1,
    name: "Ann Culhane",
    phone: "5684236526",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla...",
    status: "Open",
    rate: "$70.00",
    balance: "-$270.00",
    deposit: "$500.00",
    balanceClass: "text-danger",
    statusClass: "badge-primary",
  },
  {
    id: 2,
    name: "Ahmad Rosser",
    phone: "5684236527",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla...",
    status: "Paid",
    rate: "$70.00",
    balance: "$270.00",
    deposit: "$500.00",
    balanceClass: "text-success",
    statusClass: "badge-success",
  },
  {
    id: 3,
    name: "Zain Calzoni",
    phone: "5684236528",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla...",
    status: "Open",
    rate: "$70.00",
    balance: "-$20.00",
    deposit: "$500.00",
    balanceClass: "text-danger",
    statusClass: "badge-primary",
  },
  {
    id: 4,
    name: "Leo Stanton",
    phone: "5684236529",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla...",
    status: "Inactive",
    rate: "$70.00",
    balance: "$600.00",
    deposit: "$500.00",
    balanceClass: "text-success",
    statusClass: "badge-secondary",
  },
  {
    id: 5,
    name: "Kaiya Vetrov",
    phone: "5684236530",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla...",
    status: "Open",
    rate: "$70.00",
    balance: "-$350.00",
    deposit: "$500.00",
    balanceClass: "text-danger",
    statusClass: "badge-primary",
  },
  {
    id: 6,
    name: "Ryan Westervelt",
    phone: "5684236531",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla...",
    status: "Paid",
    rate: "$70.00",
    balance: "-$270.00",
    deposit: "$500.00",
    balanceClass: "text-danger",
    statusClass: "badge-success",
  },
  {
    id: 7,
    name: "Corey Stanton",
    phone: "5684236532",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla...",
    status: "Due",
    rate: "$70.00",
    balance: "$30.00",
    deposit: "$500.00",
    balanceClass: "text-success",
    statusClass: "badge-danger",
  },
  {
    id: 8,
    name: "Adison Aminoff",
    phone: "5684236533",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla...",
    status: "Open",
    rate: "$70.00",
    balance: "-$270.00",
    deposit: "$500.00",
    balanceClass: "text-danger",
    statusClass: "badge-primary",
  },
  {
    id: 9,
    name: "Alfredo Aminoff",
    phone: "5684236534",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla...",
    status: "Inactive",
    rate: "$70.00",
    balance: "$460.00",
    deposit: "$500.00",
    balanceClass: "text-success",
    statusClass: "badge-secondary",
  },
  {
    id: 9,
    name: "Alfredo Aminoff",
    phone: "5684236534",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla...",
    status: "Inactive",
    rate: "$70.00",
    balance: "$460.00",
    deposit: "$500.00",
    balanceClass: "text-success",
    statusClass: "badge-secondary",
  },
];
